
POST http://localhost:8000/config HTTP/1.1
Content-Type: application/json

{
    "active": true,
    "service": "file-downloader",
    "source": "channel 1",
    "provider": "br",
    "depends_on": [{
        "service": "file-downloader",
        "source": "channel 2"
    }]
}

###
POST http://localhost:8000/config HTTP/1.1
Content-Type: application/json

{
    "active": true,
    "service": "file-parser",
    "source": "channel 2",
    "provider": "br",
    "depends_on": [{
        "service": "file-downloader",
        "source": "channel 1"
    }]
}

###
PUT http://localhost:8000/config HTTP/1.1
Content-Type: application/json

{
    "active": false,
    "service": "file-downloader",
    "source": "channel 1",
    "provider": "br",
    "depends_on": [{
        "service": "file-downloader",
        "source": "channel 2"
    }]
}

###
GET http://localhost:8000/config HTTP/1.1

###
GET http://localhost:8000/config/c79214e6e49296430a7f66af00675f7e HTTP/1.1

###
DELETE http://localhost:8000/config/c79214e6e49296430a7f66af00675f7e HTTP/1.1

###
GET http://localhost:8000/config/provider/br/service/file-parser HTTP/1.1

###
GET http://localhost:8000/config/provider/br/source/channel 2 HTTP/1.1

###
GET http://localhost:8000/config/provider/br/service/file-parser/active/true HTTP/1.1

###
GET http://localhost:8000/config/provider/br/service/file-parser/source/channel 2 HTTP/1.1

###
GET http://localhost:8000/config/provider/br/dependencies/service/file-downloader/source/channel 1 HTTP/1.1
