// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
	"libs/golang/ddd/adapters/http/handlers/config-vault/handlers"
	"libs/golang/ddd/domain/entities/config-vault/entity"
	"libs/golang/ddd/domain/repositories/database/mongodb/config-vault/repository"
)

// Injectors from wire.go:

func NewWebServiceConfigHandler(client *mongo.Client, database string) *handlers.WebConfigHandler {
	configRepository := repository.NewConfigRepository(client, database)
	webConfigHandler := handlers.NewWebConfigHandler(configRepository)
	return webConfigHandler
}

// wire.go:

var setConfigRepositoryDependency = wire.NewSet(repository.NewConfigRepository, wire.Bind(
	new(entity.ConfigRepositoryInterface),
	new(*repository.ConfigRepository),
),
)
