// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
	"libs/golang/ddd/adapters/http/handlers/schema-vault/handlers"
	"libs/golang/ddd/domain/entities/schema-vault/entity"
	"libs/golang/ddd/domain/repositories/database/mongodb/schema-vault/repository"
)

// Injectors from wire.go:

func NewWebServiceSchemaHandler(client *mongo.Client, database string) *handlers.WebSchemaHandler {
	schemaRepository := repository.NewSchemaRepository(client, database)
	webSchemaHandler := handlers.NewWebSchemaHandler(schemaRepository)
	return webSchemaHandler
}

// wire.go:

var setSchemaRepositoryDependency = wire.NewSet(repository.NewSchemaRepository, wire.Bind(
	new(entity.SchemaRepositoryInterface),
	new(*repository.SchemaRepository),
),
)
